config/routes.rb
Rails.application.routes.draw do

  get  'apply' => 'apply#index'           # 入力画面
  post 'apply/confirm' => 'apply#confirm' # 確認画面
  post 'apply/thanks'  => 'apply#thanks'  # 送信完了画面

  resources :faq

  get 'abouts/student'
  get 'abouts/teacher'
  get 'abouts/price'
  get 'abouts/lesson'
  get 'abouts/askme'
  get 'abouts/memory'
  get 'abouts/1_to_1'

  get 'home/index'
  
  root 'home#index'

end

app/models/apply.rb
class Apply
  include ActiveModel::Model

  # oz/app/models/student.rb
  # http://qiita.com/k-shogo/items/5bbc23e1d0dd0ad3a8a2
  # 
  # classname    | 説明              | required?
  # ----------------------------------------------
  # :name          生徒名
  # :sex           生徒性別             y
  # :email         連絡先アドレス
  # :tel_num       連絡先電話番号        y
  # :school        学校名
  # :grade         学年[学校]           y
  # :year          学年[学年]           y
  # :purpose       通塾目的             y
  # ----------------------------------------------
  # :like_subject  好きな教科
  # :weak_subject  苦手な教科
  # :deviation     偏差値
  # :result        成績
  # :club          部活
  # :lesson        習い事
  # ----------------------------------------------
  # :school_choice 受験志望校
  # :hope          塾に求めること
  # :problem       悩み
  # :willingness   学習意欲
  # :personality   生徒の性格
  # ----------------------------------------------
  # :lesson_style  希望する授業スタイル
  # :teacher_sex   講師の性別指定
  # :extension     居残り授業の可否
  # :message       その他
  
  attr_accessor :name, :sex, :email, :tel_num, :school, :grade, :year, :purpose, 
    :like_subject, :weak_subject, :deviation, :result, :club, :lesson,
    :school_choice, :hope, :problem, :willingness, :personality,
    :lesson_style, :teacher_sex, :extension, :message
  
  validates :tel_num, :presence => {:message => '.tell_num'}
  validates :sex,     :presence => {:message => '.sex'}
  validates :grade,   :presence => {:message => '.grade'}
  validates :purpose, :presence => {:message => '.purpose'}

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || users_path
  end
end

app/controllers/apply_controller.rb
class ApplyController < ApplicationController
  def index
    #入力画面表示
    @apply = Apply.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @apply = Apply.new(params[:apply])
    if @apply.valid?
      # OK
      render :action => 'confirm'
    else
      # NG
      render :action => 'index'
    end
  end

  def thanks
    # send mail
    @apply = Apply.new(params[:apply])
    ApplyMailer.received_email(@apply).deliver

    render :action => 'thanks'
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/apply_mailer_helper.rb
module ApplyMailerHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/abouts/1_to_1.html.haml
- img = "https://s3-ap-northeast-1.amazonaws.com/kyotogood/images/"
- content_for :stylesheets do
  = stylesheet_link_tag "abouts",
                        media: "all"

#container
  .eight.offset-by-two
    %img{:src => "#{img}about/1_to_1.png"} 

  %h5.full.title
    集団指導塾と比べた個別指導塾の特徴
    
  .full.box.align_right
    .seven.box_title{:counter => 'none'}
      %h6 集団指導塾
    .five.box_image
      %img{:src => "#{img}about/1_to_1-02.png"} 
      %img{:src => "#{img}about/1_to_1-03.png"} 
    .seven.box_param
      集団授業では、ペースが自分と合っていない

  .full.box.align_left
    .seven.box_title{:counter => 'none'}
      %h6 個別指導塾
    .five.box_image
      %img{:src => "#{img}about/1_to_1-04.png"} 
      %img{:src => "#{img}about/1_to_1-05.png"} 
    .seven.box_param
      個別指導なら、お子様のペースに適した指導が可能

  .full.box.align_right
    .seven.box_title{:counter => 'none'}
      %h6 集団指導塾
    .five.box_image
      %img{:src => "#{img}about/1_to_1-06.png"} 
      %img{:src => "#{img}about/1_to_1-07.png"} 
    .seven.box_param
      集団授業では、記憶が定着する前にすすんでしまう

  .full.box.align_left
    .seven.box_title{:counter => 'none'}
      %h6 個別指導塾
    .five.box_image
      %img{:src => "#{img}about/1_to_1-08.png"} 
      %img{:src => "#{img}about/1_to_1-09.png"} 
    .seven.box_param
      個別指導なら、覚えていないところまで戻って苦手を潰せる

  %h5.full.title
    １対２授業と比べた、１対１授業の特徴
    
  .full.box.align_right
    .seven.box_title{:counter => 'none'}
      %h6 １対２指導塾
    .five.box_image
      %img{:src => "#{img}about/1_to_1-10.png"} 
      %img{:src => "#{img}about/1_to_1-11.png"} 
    .seven.box_param
      演習中は別の生徒を指導しなければいけない。。

  .full.box.align_left
    .seven.box_title{:counter => 'none'}
      %h6 １対１指導塾
    .five.box_image
      %img{:src => "#{img}about/1_to_1-12.png"} 
      %img{:src => "#{img}about/1_to_1-13.png"} 
    .seven.box_param
      ミスのパターン等を早期に発見でき、結果的に効率が良い
      
      
  .full.box.align_right
    .seven.box_title{:counter => 'none'}
      %h6 １対２指導塾
    .five.box_image
      %img{:src => "#{img}about/1_to_1-14.png"} 
      %img{:src => "#{img}about/1_to_1-15.png"} 
    .seven.box_param
      ペアの生徒との差が激しいと、どうしても不平等になってしまいます

  .full.box.align_left
    .seven.box_title{:counter => 'none'}
      %h6 １対１指導塾
    .five.box_image
      %img{:src => "#{img}about/1_to_1-16.png"} 
      %img{:src => "#{img}about/1_to_1-17.png"} 
    .seven.box_param
      苦手に合わせた宿題の出し方や、苦手を記録する時間的ゆとりがある

app/views/abouts/askme.html.haml
- img = "https://s3-ap-northeast-1.amazonaws.com/kyotogood/images/"
- content_for :stylesheets do
  = stylesheet_link_tag "abouts",
                        media: "all"

#container
  %h5.full.title
    Ask me とは？
  .full
    授業でわからなかった内容を京大生に聴き放題！<br/>
    平日18:00 ~ 21:30に京大生が駐在している学習ルーム<br/>
    (開放時間は10:00 ~ 22:00 土日祝も開放)<br/>
    
  .full.box.align_right
    .seven.box_title
      %h6 学習情報の共有
    .five.box_image
      %img{:src => "#{img}about/askme_1.png"} 
    .seven.box_param
      授業担当講師から Ask me 担当講師へ<br/>
      <em class="blue">生徒情報や授業の情報が共有</em>されています<br/>

  .full.box.align_left
    .seven.box_title
      %h6 学習情報をもとにした解説
    .five.box_image
      %img{:src => "#{img}about/askme_3.png"} 
    .seven.box_param
      生徒の学習状況がわかっているので<br/>
      Ask me 担当講師のほうから生徒へ声を掛けてくれる<br/>
      <em class="blue">自発的ではない生徒でも有効活用</em>が可能です<br/>
  
  .full.box.align_right
    .seven.box_title
      %h6 授業の質が大幅に向上
    .five.box_image
      %img{:src => "#{img}about/askme_4.png"} 
    .seven.box_param
      Ask me 担当講師から<em class="blue">解説した内容などを<br/>
      引き継いでいるので</em>スムーズに授業を<br/>
      開始することができます<br/>
      
  .full.box.align_right
    .full.box_image
      %img{:src => "#{img}about/askme_5.png"} 
    .full.box_param
      <em class="blue">宿題解説や記憶の定着、前回の授業の復習も<br/>
      Ask meで済ませてある</em>ので授業のペースも向上！<br/>
      記憶の定着と授業の質の向上で良いこと尽くし♪<br/>

app/views/abouts/lesson.html.haml
- img = "https://s3-ap-northeast-1.amazonaws.com/kyotogood/images/"
- content_for :stylesheets do
  = stylesheet_link_tag "abouts",
                        media: "all"
#container
  %h5.full.title
    体験授業の流れ
  .full.box.align_right
    .seven.box_title
      %h6 まずはお気軽にご相談ください
    .five.box_image
      %img{:src => "#{img}about/lesson_1.png"} 
    .seven.box_param
      アドバイザーがヒアリングをもとに、<br/>
      生徒カルテを作成します。<br/>
      学習の悩みや塾に来る目的、要望など<br/>
      お気軽にご相談ください。<br/>
      まずはお気軽にご相談ください
  
  .full.box.align_left
    .seven.box_title
      %h6 カルテ作成・指導方針
    .five.box_image
      %img{:src => "#{img}about/lesson_2.png"} 
    .seven.box_param
      ヒアリングをもとに生徒カルテを作成します。<br/>
      同時に指導方針を立てていきます。

  .full.box.align_right
    .seven.box_title    
      %h6 生徒にぴったりな講師をリストアップ
    .five.box_image
      %img{:src => "#{img}about/lesson_3.png"} 
    .seven.box_param
      生徒カルテをもとに生徒に<br/>
      ぴったりな先生をリストアップし、<br/>
      体験授業していただきます

  .full.box.align_left
    .seven.box_title
      %h6 体験授業
    .five.box_image
      %img{:src => "#{img}about/lesson_4.png"} 
    .seven.box_param
      実際に体験授業をしていただきます。<br/>
      1教科につき先生2人を体験可能です。<br/>
      体験後に自分によりあった講師を選択できます。

  .full.box.align_right
    .seven.box_title
      %h6 オーダーメイドカリキュラム
    .five.box_image
      %img{:src => "#{img}about/lesson_5.png"} 
    .seven.box_param
      選ばれた講師とアドバイザーがタッグを組み、<br/>
      生徒にあった専用カリキュラムを作成します。

  .full.box.align_left
    .seven.box_title
      %h6 アフターフォロー
    .five.box_image
      %img{:src => "#{img}about/lesson_6.png"} 
    .seven.box_param
      担当講師が決まった後もしっかりアフターフォローします。<br/>
      生徒と1対1の面談をすることで本音を話せます。<br/>
      親との三者懇談も行っています。<br/>

app/views/abouts/memory.html.haml
- img = "https://s3-ap-northeast-1.amazonaws.com/kyotogood/images/"
- content_for :stylesheets do
  = stylesheet_link_tag "abouts",
                        media: "all"

#container
  %h5.full.title
    記憶が定着する仕組
    
  .full.box.align_right
    .seven.box_title
      %h6 授業後、<em class="red">１時間以内</em>に授業内容をまとめる
    .five.box_image
      %img{:src => "#{img}about/memory_1.png"} 
    .seven.box_param
      脳は、記憶しても１時間で <em class="red">５６％</em>を忘れてしまいます。<br/>
      吸収したものを、<em class="red">一度アウトプット</em>しておくことで記憶が定着します
      %img{:src => "#{img}about/memory_2.png"} 
            
  .full.box.align_left
    .seven.box_title
      %h6 授業後、<em class="yellow">２日以内に復習</em>する
    .five.box_image
      %img{:src => "#{img}about/memory_3.png"} 
    .seven.box_param
      脳は1日で<em class="yellow">74％</em>を忘れてしまいます。<br/>
      <em class="yellow">2日以内に宿題</em>をすることで記憶が定着します。
      %img{:src => "#{img}about/memory_4.png"} 
            
  .full.box.align_right
    .seven.box_title
      %h6 3~4日目に宿題と定着度をチェック
    .five.box_image
      %img{:src => "#{img}about/memory_5.png"} 
    .seven.box_param
      <em class="green">次の授業日までに、 Ask Me にきて疑問を解決</em><br/>
      Ask Meには、京大生が駐在しており、即疑問を解決できます<br/>
      この仕組により理解度アップ・記憶の定着をはかります！
      %a{:href => "askme"} Ask Meをもっと詳しく
      %img{:src => "#{img}about/memory_6.png"} 
  
  .full.box.align_left
    .seven.box_title
      %h6 5~6日目にもう一度自力でやる！
    .five.box_image
      %img{:src => "#{img}about/memory_7.png"} 
    .seven.box_param
      <em class="Lblue">授業前に再度復習</em><br/>
      何度も繰り返すことで、記憶を定着させます！

app/views/abouts/price.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag "abouts",
                        "price",
                        media: "all"
- content_for :footer_javascripts do
  = javascript_include_tag "price"


- img = "https://s3-ap-northeast-1.amazonaws.com/kyotogood/images/"

#container
  #price_menu
    %input{:type => "radio", :name => "price_menu", :id => 'grade_j'} 
    %label{:class => "threeN grade_j", :for => "grade_j"} 通常講座
    %input{:type => "radio", :name => "price_menu", :id => 'grade_h', :checked => ""} 
    %label{:class => "threeN grade_h", :for => "grade_h"} 東大京大医学部
  
  #wrapper
    .full{:style => 'text-align: center;'}
      下記以外の時間でも指導可能です！<br>
      営業時間 10:00 〜　22:00 （土日祝もあいてます）
    .gradePrice.grade_j.five.offset-by-one
      .gradePrice_title 通常講座
      .gradePrice_basic ¥2,980
      .gradePrice_week.week_1
        %p ¥17,880
        %p.c.s ¥23,840
      .gradePrice_week.week_2
        %p ¥35,760
        %p.c.s ¥47,680
      .gradePrice_btn
        %a{:href => "/apply/"} 無料体験を申し込む

    .gradePrice.grade_h.five.offset-by-one.displayed
      .gradePrice_title 東大京大医学部
      .gradePrice_basic ¥3,980
      .gradePrice_week.week_1
        %p ¥23,880
        %p ¥31,840
      .gradePrice_week.week_2
        %p.c ¥47,760
        %p.c.s ¥63,680
      .gradePrice_btn
        %a{:href => "/apply/"} 無料体験を申し込む

app/views/abouts/student.html.haml
%h1 Abouts#student
%p Find me in app/views/abouts/student.html.erb

app/views/abouts/teacher.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag "abouts",
                        "teacher",
                        media: "all"
- img = "https://s3-ap-northeast-1.amazonaws.com/kyotogood/images/"

#container
  %img{:src => "#{img}about/teacher_1.png"}
    

app/views/apply/confirm.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag "apply", media: "all"
- content_for :footer_javascripts do
  = javascript_include_tag "apply"

#container
  .full.sysmes 内容に誤りがないか確認してください。
  = form_for @apply, :url => apply_thanks_path do |f|
    = f.hidden_field :name
    - name    = @apply.name
    = f.hidden_field :sex
    - sex     = @apply.sex
    = f.hidden_field :email
    - email   = @apply.email
    = f.hidden_field :tel_num
    - tel     = @apply.tel_num
    = f.hidden_field :school
    - school  = @apply.school
    = f.hidden_field :grade
    - grade   = @apply.grade
    = f.hidden_field :year
    - year    = @apply.year
    = f.hidden_field :purpose
    - purpose = @apply.purpose
    
    .group.confirm
      .six
        %label.title_label 生徒の名前
        %span= name
      .six
        %label.title_label.required 生徒の性別
        - case sex
          - when 'man'
            %span 男の子
          - when 'woman'
            %span 女の子
      .six
        %label.title_label メールアドレス
        %span= email
      .six
        %label.title_label.required 電話番号
        %span= tel
      .six
        %label.title_label 学校名
        %span= school
      .six
        %label.title_label.required 学年
        - case grade
          - when 'elementary'
            %span 小学
          - when 'junior'
            %span 中学
          - when 'high'
            %span 高校
        %span #{year}年生
      .full
        %label.title_label.required 通塾目的
        %span= purpose

    = f.submit '送信する', :class => 'btn btn-primary offset-by-three six'

app/views/apply/index.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag "apply", media: "all"
- content_for :footer_javascripts do
  = javascript_include_tag "apply"

#container
  = form_for @apply, :url => apply_confirm_path do |f|
    - if @apply.errors.any?
      .full.alert_danger{:role => "alert"}
        %strong 入力内容にエラーがあります
        - @apply.errors.each do |attr, className|
          - className
    .group
      .six
        = f.label :name, "生徒の名前", :class => 'title_label'
        = f.text_field :name, :placeholder => '生徒の名前'
      .six
        = f.label :sex, "生徒の性別", :class => 'title_label required', :require_txt => '選択必須'
        = f.radio_button :sex, 'man',   :id => "man",   :value => "男の子"
        = label_tag :sex, "男の子", :for => 'man'
        = f.radio_button :sex, 'woman', :id => "woman", :value => "女の子"
        = label_tag :sex, "女の子", :for => 'woman'
      .six
        = f.label :email, "メールアドレス", :class => 'title_label'
        = f.text_field :email, :placeholder => 'メールアドレス'
      .six
        = f.label :tel_num, "電話番号", :class => 'title_label required', :require_txt => '入力必須'
        = f.text_field :tel_num, :placeholder => '電話番号'
      .six
        = f.label :school, "学校名", :class => 'title_label'
        = f.text_field :school, :placeholder => '学校名'
      .six
        = f.label :grade, "学年", :class => 'title_label required', :require_txt => '選択必須'
        %label.selected#grade
        .select_box_wrapper
          .select_box
            = f.radio_button :grade, 'elementary', :id => "elementary", :value => "小学生"
            %label.full{:for => "elementary"} 小学校
            = f.radio_button :grade, 'junior', :id => "junior", :value => "中学校"
            %label.full{:for => "junior"} 中学校
            = f.radio_button :grade, 'high', :id => "high", :value => "高校生"
            %label.full{:for => "high"} 高校生
        %label.selected#year 
        .select_box_wrapper
          .select_box
            - for yearCounter in 1..6 do
              = f.radio_button :year, yearCounter, :id => 'year_' + yearCounter.to_s, :value => '#{yearCounter} + 年生'
              %label.full{:for => "year_#{yearCounter}"}
                = yearCounter
                年生 
      .full
        = f.label :purpose, "通塾目的", :class => 'title_label required', :require_txt => '入力必須'
        = f.text_area :purpose, :placeholder => '通塾目的'
    = f.submit '送信する', class: 'btn btn-primary offset-by-three six'

app/views/apply/thanks.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag "apply", media: "all"
- content_for :footer_javascripts do
  = javascript_include_tag "apply"

#container
  .group.thanks
    .full
      %h6 お申し込みありがとうございます
    .success_icon
      &#xe803
    .full
      生徒に合った講師を御紹介させて頂くため<br>
      プロフィールの入力にご協力ください
    -#
      %a{:href => "", :class => 'btn btn-primary offset-by-three six'} 
        プロフィールを入力する

app/views/faq/index.html.haml
%h1 Faq#index
%p Find me in app/views/faq/index.html.erb

app/views/home/index.html.haml
- img = "https://s3-ap-northeast-1.amazonaws.com/kyotogood/images/"
- content_for :stylesheets do
  = stylesheet_link_tag "home",
                        "abouts",
                        media: "all"
#container
  %h5.full.title
    Goodの特徴
  .full.box
    .seven.box_title 1. 学習アドバイザー
    .seven.box_param
      Good! には、指導講師とは別に学習アドバイザーがいます。<br/>
      <em class="Lblue">指導をするだけの塾ではなく、結果を出す</em>という想いから<br/>
      目標を見据えた上でのカリキュラムを構築します。<br/>
      悩みや問題点もしっかり伺い、解決に注力します！<br/>
      %img{:src => "#{img}about/top_01.png"}
  .full.box  
    .seven.box_title 2. オーダーメイドカリキュラム
    .seven.box_param
      学習アドバイザーと、担当講師が打合せを行い、<br/>
      お子様に合わせたカリキュラムを作成します。<br/>
      <em class="Lblue">生徒の現在の状況を把握し、<br/>
      理想と現実のギャップを埋める</em>為の、カリキュラムを作成します。<br/>
      受験には、長期的なカリキュラムが必要不可欠です<br/>

  .full.box
    .seven.box_title 3. 完全1対1指導
    .seven.box_param
      <em class="Lblue">聞くだけではなく、対話をとおした双方向授業を行います。</em><br/>
      時には、教え役を変わってもらいながら、本当の意味で理解出来ているかを確認します。<br/>
      生徒に合った効率の良い勉強法を見つけ出し、実施するには、１対１の指導が最適です。<br/>
      %a{:href => "abouts/1_to_1"} もっと詳しく
      %img{:src => "#{img}about/top_02.png"}
  .full.box
    .seven.box_title 4. 講師は全員現役京大生
    .seven.box_param
      <em class="Lblue">京大生の受験成功体験を基にした指導を致します。</em><br/>
      勉強の仕方を教えます！<br/>
      大手塾や予備校で学んだ様々な勉強のコツや現役生ならではの<br/>
      最新の学習情報を講師同士、研究会で情報共有し、切磋琢磨しています。<br/>
      %a{:href => ""} もっと詳しく
  .full.box
    .seven.box_title 5. 記憶が定着する仕組み
    .seven.box_param
      大切なのは、授業がない日に、勉強出来るかどうか！<br/>
      理解出来ても、記憶の定着しないと意味が無い！<br/>
      Good にはその仕組があります！<br/>
      %a{:href => "abouts/memory"} もっと詳しく
      %img{:src => "#{img}about/top_03.png"}
  .full.box
    .seven.box_title 6. 理解度確認テスト
    .seven.box_param
      授業前に必ずこれまでの内容を理解いているか<br/>
      確認テストを行います。<br/>
      %img{:src => "#{img}about/top_04.png"}

app/views/layouts/application.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 京大生の個別指導学習塾 Good!
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => false
    = stylesheet_link_tag "header", :media => "all", "data-turbolinks-track" => false
    = yield :stylesheets
    = javascript_include_tag "application", "data-turbolinks-track" => false
    = yield :header_javascripts
    = csrf_meta_tags
    - img = "https://s3-ap-northeast-1.amazonaws.com/kyotogood/images/"
    = analytics_init if Rails.env.production?
    
  %body
    %header
      .sixN
        = link_to '/', :class => 'logo' do
          %img{:src => "#{img}logo.png", :alt => ""} 
      .sixN
        = link_to '/apply/', :class => 'header_email' do
          %img{:src => "#{img}mail.png", :alt => ""} 
      %menu
        
        = link_to '/abouts/askme' do
          %img{:src => "#{img}head_1.png"} 
          %span Ask me!
        = link_to '/abouts/teacher' do
          %img{:src => "#{img}head_2.png"} 
          %span 講師紹介
        = link_to '/abouts/price' do
          %img{:src => "#{img}head_3.png"} 
          %span 授業料
        = link_to '/abouts/lesson' do
          %img{:src => "#{img}head_4.png"} 
          %span 体験授業
    = yield
    = yield :footer_javascripts